### ISSUE TITLE
HI Beamsie does this project still work for you as cannot get it to start

### ISSUE THREAD

**Issue by marksteven** [beamsies/gatsby-starter-auth-aws-amplify#12]
Is there supposed to be an additional Type Composer?
Thanks for any feedback.
Had a few goes at this and all failed so far.
(system mac Catalina)

success open and validate gatsby-configs - 0.037s
success load plugins - 4.910s
success onPreInit - 0.045s
success initialize cache - 0.015s
success copy gatsby files - 0.040s
success onPreBootstrap - 0.016s
success createSchemaCustomization - 0.008s
success Checking for changed pages - 0.002s
success source and transform nodes - 0.061s

 ERROR 

Missing onError handler for invocation 'building-schema', error was 'Error: Cannot create as TypeComposer the following value: Date.'. Stacktrace was 'Error: Cannot create as TypeComposer the following value: Date.
    at SchemaComposer.createTempTC (/Users/marksteven/Documents/sites/gatsby-starter-auth-aws-amplify/node_modules/graphql-compose/lib/SchemaComposer.js:365:11)
    at SchemaComposer.addAsComposer (/Users/marksteven/Documents/sites/gatsby-starter-auth-aws-amplify/node_modules/graphql-compose/lib/SchemaComposer.js:563:27)
    at createSchemaComposer (/Users/marksteven/Documents/sites/gatsby-starter-auth-aws-amplify/node_modules/gatsby/src/schema/schema-composer.js:16:18)
    at build (/Users/marksteven/Documents/sites/gatsby-starter-auth-aws-amplify/node_modules/gatsby/src/schema/index.js:104:26)
    at buildSchema (/Users/marksteven/Documents/sites/gatsby-starter-auth-aws-amplify/node_modules/gatsby/src/services/build-schema.ts:19:3)'

**Comment by beamsies** [comment]
@marksteven Have you tried the following solution at this link?:

https://github.com/gatsbyjs/gatsby/issues/13278#issuecomment-630751552

**Comment by marksteven** [comment]
Hi 
That did the trick! thanks so much
